<?php
/**
 * @var $block \Magento\Framework\View\Element\Template;
 * @var $viewModel \Training\CustomData\ViewModel\HelloWorld;
 */
$viewModel = $block->getViewModel();
?>
<?php
$collection = $viewModel->getCollection();
foreach ($collection as $item){ ?>
    <?php if($item->getId() <= 4) { ?>
        <?= $item->getId(); ?>
        <?= $item->getCustomFieldOne(); ?>
        <?= $item->getCustomFieldTwo().'</br>'; ?>
    <?php } ?>

<?php
}
?>
<?php
$itemData = $viewModel->loadById(1);
?>
<?= $itemData->getId(); ?>
<?= $itemData->getCustomFieldOne(); ?>
<?= $itemData->getCustomFieldTwo(); ?>


