<?php /** @var $block Krish\Training\Block\Frontend\Index */ ?>
<b>Using Resource Collection</b><br>
<?php
$collection = $block->getTrainingCollection();
//echo "<pre>";
foreach ($collection as $item) {
    //print_r($item->getData());
    echo $item->getFirstName() . "</br>";
}
//echo "</pre>";
?>
<b>Using Search Criteria</b><br>
<?php
$getTrainingRepositoryData = $block->getTrainingRepositoryData();
//echo "<pre>";
foreach ($getTrainingRepositoryData as $data) {
    echo $data->getFirstName() . "</br>";
}
//echo "</pre>";
?>

<div class="row">
    <div class="col-md-8">
        <form name="training_form," method="post" id="training_form" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <input name="form_key" type="hidden" value="<?php echo $block->getFormKey(); ?>">
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('First Name')) ?></span></label>
                            <div class="control">
                                <input name="first_name" id="first_name" title="First Name" value="" class="input-text"
                                       type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Last Name')) ?></span></label>
                            <div class="control">
                                <input name="last_name" id="last_name" title="Last Name" value="" class="input-text"
                                       type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Status')) ?></span></label>
                            <div class="control">
                                <select name="status" id="status" title="Status" data-validate="{required:true}"
                                        class="input-select">
                                    <option value="1"><?php /* @escapeNotVerified */
                                        echo __('Enable') ?></option>
                                    <option value="0"><?php /* @escapeNotVerified */
                                        echo __('Disable') ?></option>
                                </select>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                            escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
